
"""
M3 - WEEK 5 | PROJECT: Make your data shine!

    Due 6 Mar by 21:59 

Many datasets you have seen so far were nice and clean, and ready to be analysed. 
But, that's not the case in the real world where data is often messy - with lots of information missing, 
wrong data types, etc. Before you can start working on that kind of dataset, you need to make it tidy.

In this module project your task is to pick a dataset from the link below and do the following:

    load it to Python using an appropriate library (pandas, sqllite3, etc.)
    understand the issues (take a look at the issues section for each dataset on the given URL)
    clean the data (take care of outliers, missing values, data types, etc.)
    provide explanations for all steps you took while cleaning the data
    explore and visualize your data

You'll be working in groups of two in this project  
Please go ahead with forming your own groups, and remember that each of you in the group needs to submit it. 
And remember to write the group members on your project when submitting it.

Group formation sheet is available here. (Links to an external site.)Links to an external site.

Submit your work as a Jupyter Notebook with all the code and narrative. 

URL for the data sets: https://makingnoiseandhearingthings.com/2018/04/19/datasets-for-data-cleaning-practice/ 
(Links to an external site.)Links to an external site.

 
As part of this project, you are also expected to submit the following:

1- Self-evaluation 

2- Peer evaluation 

To be able to do the peer-evaluation you must first submit your project on Canvas.

"""

### Dataset chosen from: <br> https://www.scq.ubc.ca/so-much-candy-data-seriously/

# CANDY (CRUSH) TIME

In [1]:
# dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# MERGER COMMAND just in case
%matplotlib inline

In [2]:
# use the read_csv() function to read in the dataset from a file 
# then store it in a DataFrame
# File presented some encoding issues that needed to be sorted at loading stage
candy17_df = pd.read_csv("candyhierarchy2017.csv", encoding="latin-1") #read file into DF

In [3]:
# EXPLORING THE DATASET
# Checking loaded df
candy17_df.head(3)

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Checking nulls/NaN, df shape and datatypes
candy17_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2460 entries, 0 to 2459
Columns: 120 entries, Internal ID to Click Coordinates (x, y)
dtypes: float64(4), int64(1), object(115)
memory usage: 2.3+ MB

#### Dropping columns: Internal ID - Q7 - Q8 - Q9 - Q10 & Q12  
####  we can drop them now and recover them later if we need

In [5]:
# dropping col with information not useful 
# using df.drop("colName", axes?, inPlace?) method and assigning to new df
candy17_c_df = candy17_df.drop(["Internal ID", "Q7: JOY OTHER", "Q8: DESPAIR OTHER", "Q9: OTHER COMMENTS", "Q10: DRESS", "Unnamed: 113", "Q12: MEDIA [Daily Dish]", "Q12: MEDIA [Science]", "Q12: MEDIA [ESPN]", "Q12: MEDIA [Yahoo]"] , axis="columns")

In [6]:
# candy17_c_df = candy17_df.drop(["Q12: MEDIA [Daily Dish]", "Q12: MEDIA [Science]", "Q12: MEDIA [ESPN]", "Q12: MEDIA [Yahoo]"] , axis="columns")

In [7]:
candy17_c_df.head(3)

,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),...,Q6 | Trail Mix,Q6 | Twix,"Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein",Q6 | Vicodin,Q6 | Whatchamacallit Bars,Q6 | White Bread,Q6 | Whole Wheat anything,Q6 | York Peppermint Patties,Q11: DAY,"Click Coordinates (x, y)"
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,DESPAIR,...,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,DESPAIR,DESPAIR,DESPAIR,Sunday,"(84, 25)"
2,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# outputs a count of the number of missing values in each col, in descending order
candy17_c_df.isnull().sum().sort_values(ascending=False) # counts all the True (1) and False (0)

Q6 | JoyJoy (Mit Iodine!)               1026
Q6 | Maynards                           1024
Q6 | Reggie Jackson Bar                 1014
Q6 | Bonkers (the board game)           1006
Q6 | Sweetums (a friend to diabetes)    1002
                                        ...
Q1: GOING OUT?                           110
Q5: STATE, PROVINCE, COUNTY, ETC         100
Q3: AGE                                   84
Q4: COUNTRY                               64
Q2: GENDER                                41
Length: 110, dtype: int64

### What are we going to do with the missing values???
### Maybe drop the row with missing values above 100 or 500
### And then fill in the others???

In [9]:
# JUST SOME CODE FOR (MAYBE) LATER 

# ri_df.drop("county_name", axis="columns", inplace=True)
# ri_df.dropna(subset=["stop_date", "stop_time"], inplace=True)
# ri_df["is_arrested"] = ri_df["is_arrested"].astype("bool")
# ri_df["stop_date"].str.replace('/', '-')
# combo_datetime = ri_df["stop_date"].str.cat(ri_df["stop_time"], sep=' ')
# ri_df["combo_datetime"] = pd.to_datetime(combo_datetime)
# ri_df.set_index("combo_datetime", inplace=True)
# ## ADDITIONAL - not in course; to make row value_counts() for stop_outcome same as shape
# ri_df.dropna(subset=["stop_outcome"], inplace=True)
# #  ADDITIONAL - not in course; drop search_type column with 83232 missing values
# # ri_df.drop("search_type", axis="columns", inplace=True)
# # ri_df.info()

In [10]:
#Show all of the column names
print(candy17_c_df.columns.tolist())

['Q1: GOING OUT?', 'Q2: GENDER', 'Q3: AGE', 'Q4: COUNTRY', 'Q5: STATE, PROVINCE, COUNTY, ETC', 'Q6 | 100 Grand Bar', 'Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)', 'Q6 | Any full-sized candy bar', 'Q6 | Black Jacks', 'Q6 | Bonkers (the candy)', 'Q6 | Bonkers (the board game)', 'Q6 | Bottle Caps', "Q6 | Box'o'Raisins", 'Q6 | Broken glow stick', 'Q6 | Butterfinger', 'Q6 | Cadbury Creme Eggs', 'Q6 | Candy Corn', 'Q6 | Candy that is clearly just the stuff given out for free at restaurants', 'Q6 | Caramellos', 'Q6 | Cash, or other forms of legal tender', 'Q6 | Chardonnay', 'Q6 | Chick-o-Sticks (we donÃ•t know what that is)', 'Q6 | Chiclets', 'Q6 | Coffee Crisp', 'Q6 | Creepy Religious comics/Chick Tracts', 'Q6 | Dental paraphenalia', 'Q6 | Dots', 'Q6 | Dove Bars', 'Q6 | Fuzzy Peaches', 'Q6 | Generic Brand Acetaminophen', 'Q6 | Glow sticks', 'Q6 | Goo Goo Clusters', "Q6 | Good N' Plenty", 'Q6 | Gum from baseball cards', 'Q6 | Gummy Bears straight up', 'Q6 | Hard Candy', 'Q6 | Healthy Fruit', 'Q6 | Heath Bar', "Q6 | Hershey's Dark Chocolate", 'Q6 | HersheyÃ•s Milk Chocolate', "Q6 | Hershey's Kisses", 'Q6 | Hugs (actual physical hugs)', 'Q6 | Jolly Rancher (bad flavor)', 'Q6 | Jolly Ranchers (good flavor)', 'Q6 | JoyJoy (Mit Iodine!)', 'Q6 | Junior Mints', 'Q6 | Senior Mints', 'Q6 | Kale smoothie', 'Q6 | Kinder Happy Hippo', 'Q6 | Kit Kat', 'Q6 | LaffyTaffy', 'Q6 | LemonHeads', 'Q6 | Licorice (not black)', 'Q6 | Licorice (yes black)', 'Q6 | Lindt Truffle', 'Q6 | Lollipops', 'Q6 | Mars', 'Q6 | Maynards', 'Q6 | Mike and Ike', 'Q6 | Milk Duds', 'Q6 | Milky Way', 'Q6 | Regular M&Ms', 'Q6 | Peanut M&MÃ•s', "Q6 | Blue M&M's", "Q6 | Red M&M's", "Q6 | Green Party M&M's", "Q6 | Independent M&M's", "Q6 | Abstained from M&M'ing.", 'Q6 | Minibags of chips', 'Q6 | Mint Kisses', 'Q6 | Mint Juleps', 'Q6 | Mr. Goodbar', 'Q6 | Necco Wafers', 'Q6 | Nerds', 'Q6 | Nestle Crunch', "Q6 | Now'n'Laters", 'Q6 | Peeps', 'Q6 | Pencils', 'Q6 | Pixy Stix', 'Q6 | Real Housewives of Orange County Season 9 Blue-Ray', 'Q6 | ReeseÃ•s Peanut Butter Cups', "Q6 | Reese's Pieces", 'Q6 | Reggie Jackson Bar', 'Q6 | Rolos', 'Q6 | Sandwich-sized bags filled with BooBerry Crunch', 'Q6 | Skittles', 'Q6 | Smarties (American)', 'Q6 | Smarties (Commonwealth)', 'Q6 | Snickers', 'Q6 | Sourpatch Kids (i.e. abominations of nature)', 'Q6 | Spotted Dick', 'Q6 | Starburst', 'Q6 | Sweet Tarts', 'Q6 | Swedish Fish', 'Q6 | Sweetums (a friend to diabetes)', 'Q6 | Take 5', 'Q6 | Tic Tacs', 'Q6 | Those odd marshmallow circus peanut things', 'Q6 | Three Musketeers', 'Q6 | Tolberone something or other', 'Q6 | Trail Mix', 'Q6 | Twix', 'Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein', 'Q6 | Vicodin', 'Q6 | Whatchamacallit Bars', 'Q6 | White Bread', 'Q6 | Whole Wheat anything', 'Q6 | York Peppermint Patties', 'Q11: DAY', 'Click Coordinates (x, y)']

In [11]:
#Drop all rows that have Q6 NaN
candy17_c_r_df = candy17_c_df.dropna(subset=['Q6 | 100 Grand Bar', 'Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes)', 'Q6 | Any full-sized candy bar', 'Q6 | Black Jacks', 'Q6 | Bonkers (the candy)', 'Q6 | Bonkers (the board game)', 'Q6 | Bottle Caps', "Q6 | Box'o'Raisins", 'Q6 | Broken glow stick', 'Q6 | Butterfinger', 'Q6 | Cadbury Creme Eggs', 'Q6 | Candy Corn', 'Q6 | Candy that is clearly just the stuff given out for free at restaurants', 'Q6 | Caramellos', 'Q6 | Cash, or other forms of legal tender', 'Q6 | Chardonnay', 'Q6 | Chick-o-Sticks (we donÃ•t know what that is)', 'Q6 | Chiclets', 'Q6 | Coffee Crisp', 'Q6 | Creepy Religious comics/Chick Tracts', 'Q6 | Dental paraphenalia', 'Q6 | Dots', 'Q6 | Dove Bars', 'Q6 | Fuzzy Peaches', 'Q6 | Generic Brand Acetaminophen', 'Q6 | Glow sticks', 'Q6 | Goo Goo Clusters', "Q6 | Good N' Plenty", 'Q6 | Gum from baseball cards', 'Q6 | Gummy Bears straight up', 'Q6 | Hard Candy', 'Q6 | Healthy Fruit', 'Q6 | Heath Bar', "Q6 | Hershey's Dark Chocolate", 'Q6 | HersheyÃ•s Milk Chocolate', "Q6 | Hershey's Kisses", 'Q6 | Hugs (actual physical hugs)', 'Q6 | Jolly Rancher (bad flavor)', 'Q6 | Jolly Ranchers (good flavor)', 'Q6 | JoyJoy (Mit Iodine!)', 'Q6 | Junior Mints', 'Q6 | Senior Mints', 'Q6 | Kale smoothie', 'Q6 | Kinder Happy Hippo', 'Q6 | Kit Kat', 'Q6 | LaffyTaffy', 'Q6 | LemonHeads', 'Q6 | Licorice (not black)', 'Q6 | Licorice (yes black)', 'Q6 | Lindt Truffle', 'Q6 | Lollipops', 'Q6 | Mars', 'Q6 | Maynards', 'Q6 | Mike and Ike', 'Q6 | Milk Duds', 'Q6 | Milky Way', 'Q6 | Regular M&Ms', 'Q6 | Peanut M&MÃ•s', "Q6 | Blue M&M's", "Q6 | Red M&M's", "Q6 | Green Party M&M's", "Q6 | Independent M&M's", "Q6 | Abstained from M&M'ing.", 'Q6 | Minibags of chips', 'Q6 | Mint Kisses', 'Q6 | Mint Juleps', 'Q6 | Mr. Goodbar', 'Q6 | Necco Wafers', 'Q6 | Nerds', 'Q6 | Nestle Crunch', "Q6 | Now'n'Laters", 'Q6 | Peeps', 'Q6 | Pencils', 'Q6 | Pixy Stix', 'Q6 | Real Housewives of Orange County Season 9 Blue-Ray', 'Q6 | ReeseÃ•s Peanut Butter Cups', "Q6 | Reese's Pieces", 'Q6 | Reggie Jackson Bar', 'Q6 | Rolos', 'Q6 | Sandwich-sized bags filled with BooBerry Crunch', 'Q6 | Skittles', 'Q6 | Smarties (American)', 'Q6 | Smarties (Commonwealth)', 'Q6 | Snickers', 'Q6 | Sourpatch Kids (i.e. abominations of nature)', 'Q6 | Spotted Dick', 'Q6 | Starburst', 'Q6 | Sweet Tarts', 'Q6 | Swedish Fish', 'Q6 | Sweetums (a friend to diabetes)', 'Q6 | Take 5', 'Q6 | Tic Tacs', 'Q6 | Those odd marshmallow circus peanut things', 'Q6 | Three Musketeers', 'Q6 | Tolberone something or other', 'Q6 | Trail Mix', 'Q6 | Twix', 'Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein', 'Q6 | Vicodin', 'Q6 | Whatchamacallit Bars', 'Q6 | White Bread', 'Q6 | Whole Wheat anything', 'Q6 | York Peppermint Patties'],how='all')

In [12]:
# Outputs a count of the number of missing values in each col, in descending order

candy17_c_r_df.isnull().sum().sort_values(ascending=False) # counts all the True (1) and False (0)

Q6 | JoyJoy (Mit Iodine!)               369
Q6 | Maynards                           367
Q6 | Reggie Jackson Bar                 357
Q6 | Bonkers (the board game)           349
Q6 | Sweetums (a friend to diabetes)    345
                                       ...
Q6 | Hershey's Dark Chocolate            16
Q6 | Any full-sized candy bar            15
Q6 | HersheyÃ•s Milk Chocolate            15
Q6 | Peanut M&MÃ•s                        14
Q2: GENDER                               11
Length: 110, dtype: int64

In [13]:
candy17_c_r_df.head()

,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),...,Q6 | Trail Mix,Q6 | Twix,"Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein",Q6 | Vicodin,Q6 | Whatchamacallit Bars,Q6 | White Bread,Q6 | Whole Wheat anything,Q6 | York Peppermint Patties,Q11: DAY,"Click Coordinates (x, y)"
1,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,DESPAIR,...,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,DESPAIR,DESPAIR,DESPAIR,Sunday,"(84, 25)"
3,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,MEH,...,MEH,JOY,DESPAIR,JOY,JOY,DESPAIR,DESPAIR,DESPAIR,Sunday,"(75, 23)"
4,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,MEH,...,DESPAIR,JOY,MEH,JOY,JOY,DESPAIR,DESPAIR,JOY,Friday,"(70, 10)"
5,No,Male,NaN,NaN,NaN,JOY,DESPAIR,JOY,NaN,NaN,...,MEH,JOY,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,NaN,"(75, 23)"
7,No,Male,33,canada,ontario,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,...,DESPAIR,JOY,JOY,MEH,DESPAIR,DESPAIR,DESPAIR,DESPAIR,Friday,"(55, 5)"

In [14]:
# Format similar strings to the same in different categories (like country, state)

In [24]:
from fuzzywuzzy import process,fuzz

In [20]:
for col in candy17_c_r_df[['Q1: GOING OUT?','Q2: GENDER','Q4: COUNTRY','Q5: STATE, PROVINCE, COUNTY, ETC']]:
    print('Number of unique values in ' + str(col) +': ' + str(candy17_c_r_df[col].nunique()))

Number of unique values in Q1: GOING OUT?: 2
Number of unique values in Q2: GENDER: 4
Number of unique values in Q4: COUNTRY: 101
Number of unique values in Q5: STATE, PROVINCE, COUNTY, ETC: 433

In [21]:
unique_gender = candy17_c_r_df['Q2: GENDER'].unique().tolist()
print(unique_gender)

['Male', 'Female', "I'd rather not say", 'Other', nan]

In [22]:
unique_country = candy17_c_r_df['Q4: COUNTRY'].unique().tolist()
print(unique_country)

['USA ', 'us', 'usa', nan, 'canada', 'Canada', 'Us', 'US', 'Murica', 'USA', 'uk', 'United States', 'united states', 'Usa', 'United staes', 'United Kingdom', 'United States of America', 'UAE', 'United States ', 'England', 'canada ', 'United states', 'u.s.a.', 'USAUSAUSA', 'america', 'france', 'United States of America ', 'U.S.A.', 'Mexico', 'Canada ', 'united states of america', 'US of A', 'UK', 'Unites States', 'The United States', 'North Carolina ', 'Netherlands', 'Europe', 'Earth', 'U S', 'u.s.', 'Costa Rica', 'The United States of America', 'cascadia', 'insanity lately', 'Greece', 'USA? Hard to tell anymore..', "'merica", 'Pittsburgh', 'United State', 'France', 'U.S.', 'A', 'Can', 'Canae', 'New York', 'Trumpistan', 'Ireland', 'United Sates', 'Korea', 'Australia', 'California', 'Japan', 'USa', 'South africa', 'I pretend to be from Canada, but I am really from the United States.', 'Usa ', 'Iceland', 'Canada`', 'Scotland', 'Denmark', 'France ', 'Uk', 'Switzerland', 'Ahem....Amerca', 'South Korea', 'New Jersey', 'CANADA', 'United Stated', 'Germany', 'America', 'United Statss', 'endland', 'Atlantis', 'murrika', 'Alaska', 'united States ', 'germany', 'N. America', 'Singapore', 'USSA', 'Taiwan', 'China', 'spain', 'U.S. ', 'Narnia', 'u s a', 'United Statea', 'subscribe to dm4uz3 on youtube', 'USA USA USA!!!!', "I don't know anymore", 'Fear and Loathing']

In [36]:
process.extract('us', unique_country, scorer=fuzz.token_set_ratio, limit=None)

[('us', 100),
 ('Us', 100),
 ('US', 100),
 ('US of A', 100),
 ('USA ', 80),
 ('usa', 80),
 ('USA', 80),
 ('Usa', 80),
 ('USa', 80),
 ('Usa ', 80),
 ('USA USA USA!!!!', 80),
 ('USSA', 67),
 ('uk', 50),
 ('UK', 50),
 ('Uk', 50),
 ('UAE', 40),
 ('U S', 40),
 ('u.s.', 40),
 ('U.S.', 40),
 ('U.S. ', 40),
 ('USAUSAUSA', 36),
 ('Australia', 36),
 ('Trumpistan', 33),
 ('u.s.a.', 29),
 ('U.S.A.', 29),
 ('spain', 29),
 ('u s a', 29),
 ('Unites States', 27),
 ('Murica', 25),
 ('Europe', 25),
 ('Alaska', 25),
 ('murrika', 22),
 ('cascadia', 20),
 ('Scotland', 20),
 ('Atlantis', 20),
 ('Singapore', 18),
 ('Costa Rica', 17),
 ('Pittsburgh', 17),
 ('New Jersey', 17),
 ('Netherlands', 15),
 ('USA? Hard to tell anymore..', 15),
 ('Switzerland', 15),
 ('South Korea', 15),
 ('United staes', 14),
 ('United State', 14),
 ('United Sates', 14),
 ('South africa', 14),
 ('United States', 13),
 ('united states', 13),
 ('United States ', 13),
 ('United states', 13),
 ('United Stated', 13),
 ('United Statss', 13),
 ('united States ', 13),
 ('United Statea', 13),
 ('United Kingdom', 12),
 ('insanity lately', 12),
 ('subscribe to dm4uz3 on youtube', 12),
 ('The United States', 11),
 ('United States of America', 8),
 ('United States of America ', 8),
 ('united states of america', 8),
 ('The United States of America', 7),
 ('I pretend to be from Canada, but I am really from the United States.', 7),
 (nan, 0),
 ('canada', 0),
 ('Canada', 0),
 ('England', 0),
 ('canada ', 0),
 ('america', 0),
 ('france', 0),
 ('Mexico', 0),
 ('Canada ', 0),
 ('North Carolina ', 0),
 ('Earth', 0),
 ('Greece', 0),
 ("'merica", 0),
 ('France', 0),
 ('A', 0),
 ('Can', 0),
 ('Canae', 0),
 ('New York', 0),
 ('Ireland', 0),
 ('Korea', 0),
 ('California', 0),
 ('Japan', 0),
 ('Iceland', 0),
 ('Canada`', 0),
 ('Denmark', 0),
 ('France ', 0),
 ('Ahem....Amerca', 0),
 ('CANADA', 0),
 ('Germany', 0),
 ('America', 0),
 ('endland', 0),
 ('germany', 0),
 ('N. America', 0),
 ('Taiwan', 0),
 ('China', 0),
 ('Narnia', 0),
 ("I don't know anymore", 0),
 ('Fear and Loathing', 0)]

In [37]:
process.extract('america', unique_country, scorer=fuzz.token_set_ratio, limit=None)

[('United States of America', 100),
 ('america', 100),
 ('United States of America ', 100),
 ('united states of america', 100),
 ('The United States of America', 100),
 ('America', 100),
 ('N. America', 100),
 ("'merica", 92),
 ('Murica', 77),
 ('Ahem....Amerca', 67),
 ('Mexico', 62),
 ('Narnia', 62),
 ('Costa Rica', 59),
 ('murrika', 57),
 ('South africa', 53),
 ('Australia', 50),
 ('California', 47),
 ('Taiwan', 46),
 ('Iceland', 43),
 ('Germany', 43),
 ('germany', 43),
 ('UAE', 40),
 ('cascadia', 40),
 ('Can', 40),
 ('North Carolina ', 38),
 ('Trumpistan', 35),
 ('Netherlands', 33),
 ('Earth', 33),
 ('Canae', 33),
 ('Korea', 33),
 ('Japan', 33),
 ('Switzerland', 33),
 ('China', 33),
 ('spain', 33),
 ('Fear and Loathing', 33),
 ('United staes', 32),
 ('USA? Hard to tell anymore..', 32),
 ('United State', 32),
 ('United Sates', 32),
 ('canada', 31),
 ('Canada', 31),
 ('canada ', 31),
 ('france', 31),
 ('Canada ', 31),
 ('Europe', 31),
 ('Greece', 31),
 ('France', 31),
 ('Canada`', 31),
 ('France ', 31),
 ('CANADA', 31),
 ('Alaska', 31),
 ('United States', 30),
 ('united states', 30),
 ('United States ', 30),
 ('United states', 30),
 ('Unites States', 30),
 ('United Stated', 30),
 ('united States ', 30),
 ('United Statea', 30),
 ("I don't know anymore", 30),
 ('England', 29),
 ('Ireland', 29),
 ('Denmark', 29),
 ('endland', 29),
 ('insanity lately', 27),
 ('New York', 27),
 ('Scotland', 27),
 ('Atlantis', 27),
 ('USAUSAUSA', 25),
 ('The United States', 25),
 ('A', 25),
 ('Singapore', 25),
 ('New Jersey', 24),
 ('South Korea', 22),
 ('USA ', 20),
 ('usa', 20),
 (nan, 20),
 ('USA', 20),
 ('Usa', 20),
 ('USa', 20),
 ('Usa ', 20),
 ('United Statss', 20),
 ('USA USA USA!!!!', 20),
 ('United Kingdom', 19),
 ('I pretend to be from Canada, but I am really from the United States.', 18),
 ('USSA', 18),
 ('u.s.a.', 17),
 ('U.S.A.', 17),
 ('u s a', 17),
 ('subscribe to dm4uz3 on youtube', 16),
 ('US of A', 14),
 ('Pittsburgh', 12),
 ('us', 0),
 ('Us', 0),
 ('US', 0),
 ('uk', 0),
 ('UK', 0),
 ('U S', 0),
 ('u.s.', 0),
 ('U.S.', 0),
 ('Uk', 0),
 ('U.S. ', 0)]